### ISSUE TITLE
PRELOAD_MKL not set 

### ISSUE THREAD

**Issue by ianlienfa** [yungyuc/nsdhw_22sp#113]
@yungyuc

Hi teacher, 

I've set up a same environment in docker on my computer.
My way to eliminate the linking error of mkl is to run `export PRELOAD_MKL=1` before running  `../validate.py'
However I couldn't do this for the GitHub action, and this variable seems to be unset at running.
I've tried to set it in the makefile, but it seems that for makefile runs in another child process, so the variable exporting doesn't work.

Is there any recommended work around for this problem?

**Comment by yungyuc** [comment]
The validation script is implemented to check whether the file `PRELOAD_MKL` exist in your directory: https://github.com/yungyuc/nsdhw_22sp/blob/8537fd081e888c83562c9a625eead89a2b45b607/hw3/validate.py#L10

Does that work for you?

**Comment by ianlienfa** [comment]
@yungyuc 
It doesn't work.
Is it possible that we need to add an `export` before the variable assignment?

**Comment by ianlienfa** [comment]
Ok, so my conclusion is that, if we change the if statement into this
```py

if [ -n "PRELOAD_MKL" ] ; then
    export PRELOAD_MKL=1
fi
```
then it works

**Comment by yungyuc** [comment]
> @yungyuc
> It doesn't work.
> Is it possible that we need to add an `export` before the variable assignment?

Could you post a link to the changeset and the CI log for how it fails?

**Comment by yungyuc** [comment]
> Ok, so my conclusion is that, if we change the if statement into this
> 
> ```python
> if [ -n "PRELOAD_MKL" ] ; then
>     export PRELOAD_MKL=1
> fi
> ```
> 
> then it works

This unconditionally preload MKL and is not an option.

**Comment by ianlienfa** [comment]
> > @yungyuc
> > It doesn't work.
> > Is it possible that we need to add an `export` before the variable assignment?
> 
> Could you post a link to the changeset and the CI log for how it fails?

Sure, here's the CI log
And sorry I don't quite understand what you mean by "posting a link to the changeset"

https://github.com/yungyuc/nsdhw_22sp/pull/105/checks?sha=6afddfb2bb49358f73d9ccd56ec93c51e8f543f7#step:5:30

<img width="964" alt="image" src="https://user-images.githubusercontent.com/46861283/161050980-1e6300ca-03f2-4718-b855-4d4315140332.png">

**Comment by yungyuc** [comment]
> > > @yungyuc
> > > It doesn't work.
> > > Is it possible that we need to add an `export` before the variable assignment?
> > 
> > 
> > Could you post a link to the changeset and the CI log for how it fails?
> 
> Sure, here's the CI log And sorry I don't quite understand what you mean by "posting a link to the changeset"

Like https://github.com/yungyuc/nsdhw_22sp/pull/105/commits/ee86514e8a4816b3eeeefd1fc2fd7e9af079c63c

> 
> https://github.com/yungyuc/nsdhw_22sp/pull/105/checks?sha=6afddfb2bb49358f73d9ccd56ec93c51e8f543f7#step:5:30
> 
> <img alt="image" width="964" src="https://user-images.githubusercontent.com/46861283/161050980-1e6300ca-03f2-4718-b855-4d4315140332.png">

In https://github.com/yungyuc/nsdhw_22sp/pull/105/files I am not seeing the file `PRELOAD_MKL`:

<img width="306" alt="image" src="https://user-images.githubusercontent.com/399122/161053560-e4ec415a-7e51-4715-9739-c96c483ac4c7.png">

Perhaps you didn't understand the meaning of the line [I posted above](https://github.com/yungyuc/nsdhw_22sp/issues/113#issuecomment-1084200340):

https://github.com/yungyuc/nsdhw_22sp/blob/8537fd081e888c83562c9a625eead89a2b45b607/hw3/validate.py#L10

Please read https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_07_01.html .

**Comment by ianlienfa** [comment]
Ahh... I see what I'm misunderstanding here.
Thanks! It works after adding that file!
