### ISSUE TITLE
How is the vector testing part of hw2 graded?

### ISSUE THREAD

**Issue by ianlienfa** [yungyuc/nsdhw_22sp#64]
Hi teacher, 
I'm wondering how we should implement the vector testing part of hw2
What I see in the validation script now is only some comments on the test requirements
And do we have to implement vector as class?

**Comment by yungyuc** [comment]
You do not have to make a class for the vector, but you may.  You should use C++ to implement the vector.  The purpose of the second question is to help you get familiar with pybind11.  You will need to wrap your C++ code to Python and then test it.

**Comment by ianlienfa** [comment]
Got it. Thanks!
