### ISSUE TITLE
Hw2 question and some readme typo

### ISSUE THREAD

**Issue by harry900831** [yungyuc/nsdhw_22sp#68]
Hi, 
I would like to make sure that we only have to implement the class that at least contains the member function listed below in hw2, right?
```cpp
class Line
{
public:
    Line();
    Line(Line const & );
    Line(Line       &&);
    Line & operator=(Line const & );
    Line & operator=(Line       &&);
    Line(size_t size);
    ~Line();
    size_t size() const;
    const float & x(size_t it) const;
    float & x(size_t it);
    const float & y(size_t it) const;
    float & y(size_t it);
private:
    // Member data.
}; /* end class Line */
```

And I think there's a typo in readme of hw2:
 `float& x(size_t it) const;` should return `const float&` instead of `float&`.
 In grading guideline of hw0: 
 This homework assignment has 1 points (instead of 5).
 
 Thanks in advance!

**Comment by yungyuc** [comment]
Correct.  And thanks for spotting the typos.  It helps.
